resources:
  - ../../base
  - loadbalancer.yaml

images:
  - name: ghcr.io/huyhoangTran05/organica
    newTag: "sha-b25fcae4ec52961ef2ee58720f2cc480f3e8e3fe"

patchesStrategicMerge:
  - patch-replicas.yaml
  - patch-env.yaml
  - patch-env.yaml
