resources:
  - ../../base
  - loadbalancer.yaml

images:
  - name: ghcr.io/Manhnd395/organica
    newTag: "sha-db978a80f42104961ecff0ba71fff09dee03edc8"

patchesStrategicMerge:
  - patch-replicas.yaml
  - patch-env.yaml
  - patch-env.yaml
