resources:
  - ../../base
  - loadbalancer.yaml

images:
  - name: ghcr.io/huyhoangTran05/organica
    newTag: "sha-768c00cb4ba8fb698bd2deab3bce31db25538746"

patchesStrategicMerge:
  - patch-replicas.yaml
  - patch-env.yaml
