apiVersion: apps/v1
kind: Deployment
metadata:
  name: organica
spec:
  template:
    spec:
      containers:
        - name: organica
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: MONGO_URL
              value: "mongodb://mongo:27017"
            - name: DB_NAME
              value: "organica"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"